import type { ClimateRule } from '../../types';

export const XIN_YIN_CLIMATE_RULES: ClimateRule[] = [
  {
    id: 'yin-month-xin-ji-ren-visible-geng-hidden-jia-control',
    label: '辛日寅月己壬两透支见庚制甲科甲规则',
    description:
      '辛金生寅月，寒未尽退，传统以己为君、壬为臣；若己壬两透，而地支又见庚金制甲，较合原文"己壬两透，支见庚制甲，科甲定然"，不应仍停留在一般春金调候层。',
    months: ['寅'],
    dayMasters: ['金'],
    dayStems: ['辛'],
    requiredVisibleStems: ['己', '壬'],
    requiredHiddenStems: ['庚'],
    usefulWuxing: '土',
    favorableOrder: ['土', '水', '金'],
    traceHints: ['取用层次:己壬两透，支见庚制甲', '成格层次:科甲定然'],
    hint: '辛金寅月己壬两透而支见庚制甲，多主科甲',
  },
  {
    id: 'yin-month-xin-ji-visible-jia-hidden-alt-grace',
    label: '辛日寅月己透支有甲异路恩荣规则',
    description:
      '辛金生寅月，若己土透干，而甲木只在地支暗见，较合原文"己土透干，支中有甲，异路恩荣"；此类层次低于己壬两透科甲，但不应误落到贫贱或富贵难全。',
    months: ['寅'],
    dayMasters: ['金'],
    dayStems: ['辛'],
    requiredVisibleStems: ['己'],
    requiredHiddenStems: ['甲'],
    forbiddenVisibleStems: ['甲'],
    usefulWuxing: '土',
    favorableOrder: ['土', '水'],
    traceHints: ['取用层次:己土透干，支中有甲', '成格层次:异路恩荣'],
    hint: '辛金寅月己土透而支中有甲，可作异路恩荣',
  },
  {
    id: 'yin-month-xin-ren-visible-no-ji-geng-poor',
    label: '辛日寅月见壬无己庚贫贱规则',
    description:
      '辛金生寅月，若只见壬水而全无己土、庚金为辅，较合原文"或见壬，无己庚者，贫贱之徒"；此时臣有而君佐俱失，不应误按壬水得用上断。',
    months: ['寅'],
    dayMasters: ['金'],
    dayStems: ['辛'],
    requiredVisibleStems: ['壬'],
    maxStemTotalCounts: {
      己: 0,
      庚: 0,
    },
    usefulWuxing: '土',
    favorableOrder: ['土', '金'],
    traceHints: ['破格因素:见壬而无己庚', '成格层次:贫贱之徒'],
    hint: '辛金寅月见壬而无己庚，多主贫贱',
  },
  {
    id: 'yin-month-xin-ren-visible-geng-no-ji-incomplete',
    label: '辛日寅月壬透庚存己不全难全规则',
    description:
      '辛金生寅月，原文于己壬两透与无己庚贫贱之间，另有"己土不全，号曰君臣失势，富贵难全"一层。依上下文推断，若壬水已透、庚金尚存，而己土不透，则较合此象：较贫贱为高，却不足以入科甲恩荣。',
    months: ['寅'],
    dayMasters: ['金'],
    dayStems: ['辛'],
    requiredVisibleStems: ['壬'],
    forbiddenVisibleStems: ['己'],
    minStemTotalCounts: {
      庚: 1,
    },
    usefulWuxing: '土',
    favorableOrder: ['土', '金', '水'],
    traceHints: ['破格因素:己土不全，君臣失势', '成格层次:富贵难全'],
    hint: '辛金寅月壬透而己不全、庚尚存，多主富贵难全',
  },
  {
    id: 'yin-month-xin-bing-visible-martial',
    label: '辛日寅月丙透武学规则',
    description:
      '辛金生寅月，原文明言"或有丙火出干，亦主武学"。此条不宜与己壬两透科甲或见壬无己庚贫贱混断，应单列为偏武职、偏技艺进身的一层。',
    months: ['寅'],
    dayMasters: ['金'],
    dayStems: ['辛'],
    requiredVisibleStems: ['丙'],
    forbiddenVisibleStems: ['壬'],
    usefulWuxing: '火',
    favorableOrder: ['火', '土'],
    traceHints: ['取用层次:丙火出干', '成格层次:亦主武学'],
    hint: '辛金寅月丙火出干，多主武学之途',
  },
  {
    id: 'yin-month-xin-fire-formation-ren-only-ordinary',
    label: '辛日寅月火局壬透不克己常人规则',
    description:
      '辛金生寅月，若地支火局已成，即便壬水出干，仍不能克制己土燥势，较合原文"支成火局，即壬水出干，不克己土，亦寻常之人"；不应误把见壬当作足以破局。',
    months: ['寅'],
    dayMasters: ['金'],
    dayStems: ['辛'],
    requiredFormationWuxings: ['火'],
    requiredVisibleStems: ['壬'],
    minStemTotalCounts: {
      己: 1,
    },
    forbiddenVisibleStems: ['庚'],
    usefulWuxing: '水',
    favorableOrder: ['水', '土'],
    traceHints: ['破格因素:支成火局，壬透仍不能克己', '成格层次:寻常之人'],
    hint: '辛金寅月火局成势而仅壬透，多作寻常之人',
  },
  {
    id: 'yin-month-xin-fire-formation-geng-ren-all-distinguished',
    label: '辛日寅月火局庚壬两透显达规则',
    description:
      '辛金生寅月，若地支火局成势，而庚壬两透协力破局制火，较合原文"庚壬两透，破局制火，必为显达之人"；此类明显高于火局见壬常人。',
    months: ['寅'],
    dayMasters: ['金'],
    dayStems: ['辛'],
    requiredFormationWuxings: ['火'],
    requiredVisibleStems: ['庚', '壬'],
    usefulWuxing: '金',
    favorableOrder: ['金', '水'],
    traceHints: ['取用层次:支成火局，庚壬两透破局制火', '成格层次:必为显达之人'],
    hint: '辛金寅月火局成势而庚壬两透，多主显达',
  },
  {
    id: 'yin-month-xin-water-formation-no-bing-ordinary',
    label: '辛日寅月水局无丙沉寒平常规则',
    description:
      '辛金生寅月，若地支成水局而不见丙火透出，较合原文"金弱沉寒，平常之士"；此类寒气到底，不应仍按水局有情上断。',
    months: ['寅'],
    dayMasters: ['金'],
    dayStems: ['辛'],
    requiredFormationWuxings: ['水'],
    forbiddenVisibleStems: ['丙'],
    usefulWuxing: '火',
    favorableOrder: ['火', '土'],
    traceHints: ['破格因素:支成水局而不见丙火', '成格层次:金弱沉寒，平常之士'],
    hint: '辛金寅月水局成势而无丙，多作平常之士',
  },
  {
    id: 'yin-month-xin-water-formation-bing-visible-rich',
    label: '辛日寅月水局得丙照暖富贵规则',
    description:
      '辛金生寅月，若地支成水局而丙火透干照暖，较合原文"得丙透照暖，反主富贵"；此类不应仍按沉寒平常处理。',
    months: ['寅'],
    dayMasters: ['金'],
    dayStems: ['辛'],
    requiredFormationWuxings: ['水'],
    requiredVisibleStems: ['丙'],
    usefulWuxing: '火',
    favorableOrder: ['火', '土', '水'],
    traceHints: ['取用层次:支成水局，得丙透照暖', '成格层次:反主富贵'],
    hint: '辛金寅月水局成势而丙透照暖，反主富贵',
  },
];
