import type { ClimateRule } from '../../types';

export const GENG_CHEN_CLIMATE_RULES: ClimateRule[] = [
  {
    id: 'chen-month-geng-jia-ding-first',
    label: '庚日辰月先甲后丁规则',
    description: '庚金生辰月，戊土司令，先用甲疏土，后用丁炼金。',
    priority: 119,
    months: ['辰'],
    dayMasters: ['金'],
    dayStems: ['庚'],
    usefulWuxing: '木',
    favorableOrder: ['木', '火'],
    hint: '庚金辰月，先甲疏土，后丁炼金',
  },
  {
    id: 'chen-month-geng-jia-ding-visible-no-peer',
    label: '庚日辰月丁甲两透无比肩科甲规则',
    description: '庚金生辰月，丁甲两透而不见比肩，科甲之命。',
    priority: 123,
    months: ['辰'],
    dayMasters: ['金'],
    dayStems: ['庚'],
    requiredVisibleStems: ['丁', '甲'],
    maxVisibleStemCounts: { 庚: 1 },
    usefulWuxing: '木',
    favorableOrder: ['木', '火'],
    traceHints: ['取用层次:丁甲两透，不见比肩', '成格层次:科甲'],
    hint: '庚金辰月丁甲两透且不见比肩，可论科甲',
  },
  {
    id: 'chen-month-geng-jia-hidden-ding-visible',
    label: '庚日辰月甲藏丁透异路规则',
    description: '庚金生辰月，甲木藏支、丁火透干，异路功名。',
    priority: 122,
    months: ['辰'],
    dayMasters: ['金'],
    dayStems: ['庚'],
    requiredVisibleStems: ['丁'],
    requiredHiddenStems: ['甲'],
    maxVisibleStemCounts: { 甲: 0 },
    usefulWuxing: '火',
    favorableOrder: ['火', '木'],
    traceHints: ['取用层次:甲藏丁透', '成格层次:异路功名'],
    hint: '庚金辰月甲藏丁透，异路功名',
  },
];
