import type { ClimateRule } from '../../types';

export const GENG_MAO_CLIMATE_RULES: ClimateRule[] = [
  {
    id: 'mao-month-geng-ding-first',
    label: '庚日卯月专用丁火规则',
    description: '庚金生卯月，专用丁火，借甲引丁，借庚劈甲。',
    priority: 118,
    months: ['卯'],
    dayMasters: ['金'],
    dayStems: ['庚'],
    usefulWuxing: '火',
    favorableOrder: ['火', '木', '金'],
    hint: '庚金卯月，专用丁火，甲引丁、庚劈甲',
  },
  {
    id: 'mao-month-geng-ding-jia-visible-geng-hidden',
    label: '庚日卯月丁甲透支见庚规则',
    description: '庚金生卯月，丁甲两透，支下再见庚金制甲；配得中和，方论大贵。',
    priority: 123,
    months: ['卯'],
    dayMasters: ['金'],
    dayStems: ['庚'],
    requiredVisibleStems: ['丁', '甲'],
    requiredHiddenStems: ['庚'],
    usefulWuxing: '火',
    favorableOrder: ['火', '木', '金'],
    traceHints: ['取用层次:丁甲两透，支见庚金'],
    hint: '庚金卯月丁甲两透、支见庚制甲，得中和方论大贵',
  },
  {
    id: 'mao-month-geng-bing-without-ding',
    label: '庚日卯月无丁有丙异路规则',
    description: '庚金生卯月，无丁而有丙，异路功名。',
    priority: 122,
    months: ['卯'],
    dayMasters: ['金'],
    dayStems: ['庚'],
    requiredVisibleStems: ['丙'],
    maxStemTotalCounts: { 丁: 0 },
    usefulWuxing: '火',
    favorableOrder: ['火', '木'],
    traceHints: ['取用层次:无丁有丙', '成格层次:异路功名'],
    hint: '庚金卯月无丁有丙，异路功名',
  },
];
