import type { ClimateRule } from '../../types';

export const REN_CHEN_CLIMATE_RULES: ClimateRule[] = [
  {
    id: 'chen-month-ren-jia-geng-first',
    label: '壬日辰月先甲后庚规则',
    description: '壬水生辰月，戊土司权，先用甲木疏土，次取庚金发源。',
    priority: 118,
    months: ['辰'],
    dayMasters: ['水'],
    dayStems: ['壬'],
    usefulWuxing: '木',
    favorableOrder: ['木', '金'],
    hint: '壬水辰月，先甲疏土，次取庚金',
  },
  {
    id: 'chen-month-ren-jia-geng-visible',
    label: '壬日辰月甲庚俱透科甲规则',
    description: '壬水生辰月，甲庚俱透，科甲定然。',
    priority: 123,
    months: ['辰'],
    dayMasters: ['水'],
    dayStems: ['壬'],
    requiredVisibleStems: ['甲', '庚'],
    usefulWuxing: '木',
    favorableOrder: ['木', '金'],
    traceHints: ['取用层次:甲庚俱透', '成格层次:科甲'],
    hint: '壬水辰月甲庚俱透，科甲定然',
  },
  {
    id: 'chen-month-ren-jia-visible-geng-hidden',
    label: '壬日辰月甲透庚藏修齐规则',
    description: '壬水生辰月，甲透而庚藏，修齐品格。',
    priority: 122,
    months: ['辰'],
    dayMasters: ['水'],
    dayStems: ['壬'],
    requiredVisibleStems: ['甲'],
    requiredHiddenStems: ['庚'],
    maxVisibleStemCounts: { 庚: 0 },
    usefulWuxing: '木',
    favorableOrder: ['木', '金'],
    traceHints: ['取用层次:甲透庚藏', '成格层次:修齐品格'],
    hint: '壬水辰月甲透庚藏，可论修齐品格',
  },
];
