import type { ClimateRule } from '../../types';

export const REN_YIN_CLIMATE_RULES: ClimateRule[] = [
  {
    id: 'yin-month-ren-geng-bing-wu',
    label: '壬日寅月庚丙戊次第规则',
    description:
      '壬水生寅月，失令而寒，传统多先取庚金发源，次取丙火除寒，再取戊土止流，较单用金水更完整。',
    priority: 121,
    months: ['寅'],
    dayMasters: ['水'],
    dayStems: ['壬'],
    usefulWuxing: '金',
    favorableOrder: ['金', '火', '土'],
    hint: '壬水寅月，先庚次丙，再酌戊土',
  },
  {
    id: 'yin-month-ren-geng-bing-first',
    label: '壬日寅月先庚次丙规则',
    description: '壬水生寅月，失令而寒，传统多先取庚金发源，次取丙火除寒，较单用金水更完整。',
    priority: 120,
    months: ['寅'],
    dayMasters: ['水'],
    dayStems: ['壬'],
    usefulWuxing: '金',
    favorableOrder: ['金', '火'],
    hint: '壬水寅月，先庚次丙',
  },
  {
    id: 'yin-month-ren-geng-bing-wu-visible',
    label: '壬日寅月庚丙戊齐透科甲规则',
    description: '壬水生寅月，庚金发源、丙火佐助、戊土止流；庚丙戊齐透，科甲功名。',
    priority: 124,
    months: ['寅'],
    dayMasters: ['水'],
    dayStems: ['壬'],
    requiredVisibleStems: ['庚', '丙', '戊'],
    usefulWuxing: '金',
    favorableOrder: ['金', '火', '土'],
    traceHints: ['取用层次:庚丙戊三者齐透', '成格层次:科甲功名'],
    hint: '壬水寅月庚丙戊齐透，科甲功名',
  },
  {
    id: 'yin-month-ren-geng-first-bing-assist',
    label: '壬日寅月庚金为先丙火为佐规则',
    description: '壬水生寅月，庚金发源为主，丙火除寒为佐，较简单金水扶抑更贴合原法。',
    priority: 120,
    months: ['寅'],
    dayMasters: ['水'],
    dayStems: ['壬'],
    usefulWuxing: '金',
    favorableOrder: ['金', '火'],
    hint: '壬水寅月，庚金为先，丙火为佐',
  },
];
