import type { ClimateRule } from '../../types';

export const REN_ZI_CLIMATE_RULES: ClimateRule[] = [
  {
    id: 'zi-month-ren-wu-bing',
    label: '壬日子月戊丙并用规则',
    description:
      '壬水生子月，寒旺需堤，戊土止流为先，丙火暖局为后。戊丙两透，富贵可期，不宜仍按冬水只取火概之。',
    months: ['子'],
    dayMasters: ['水'],
    dayStems: ['壬'],
    usefulWuxing: '土',
    favorableOrder: ['土', '火'],
    hint: '壬水子月，戊土止流，丙火暖局，戊丙两透富贵',
  },
  {
    id: 'zi-month-ren-wu-no-bing',
    label: '壬日子月有戊无丙富真贵假规则',
    description:
      '壬水生子月，若戊透而丙不出，虽能止流却寒气不解，较合原文"有戊无丙，富真贵假"；不应仍按戊丙两透富贵上断。',
    months: ['子'],
    dayMasters: ['水'],
    dayStems: ['壬'],
    requiredVisibleStems: ['戊'],
    maxStemTotalCounts: { 丙: 0 },
    usefulWuxing: '土',
    favorableOrder: ['土', '火'],
    traceHints: ['取用层次:有戊无丙', '成格层次:富真贵假'],
    hint: '壬水子月戊透而丙不出，多主富真贵假',
  },
  {
    id: 'zi-month-ren-bing-no-wu',
    label: '壬日子月有丙无戊虚名规则',
    description:
      '壬水生子月，若丙透而戊不出，虽能暖局却无堤防，较合原文"有丙无戊，虚名虚利"；不应仍按戊丙两透富贵论。',
    months: ['子'],
    dayMasters: ['水'],
    dayStems: ['壬'],
    requiredVisibleStems: ['丙'],
    maxStemTotalCounts: { 戊: 0 },
    usefulWuxing: '土',
    favorableOrder: ['土', '火'],
    traceHints: ['取用层次:有丙无戊', '成格层次:虚名虚利'],
    hint: '壬水子月丙透而戊不出，多主虚名虚利',
  },
  {
    id: 'zi-month-ren-no-wu-bing',
    label: '壬日子月戊丙俱无泛滥规则',
    description:
      '壬水生子月，水旺无堤无暖，泛滥成灾，较合原文"戊丙俱无，泛滥无依"；不应仍按冬水泛化处理。',
    months: ['子'],
    dayMasters: ['水'],
    dayStems: ['壬'],
    maxStemTotalCounts: { 戊: 0, 丙: 0 },
    usefulWuxing: '土',
    favorableOrder: ['土', '火'],
    traceHints: ['破格因素:戊丙俱无', '成格层次:泛滥无依'],
    hint: '壬水子月戊丙俱无，多作泛滥无依之命',
  },
  {
    id: 'zi-month-ren-water-formation-no-fire',
    label: '壬日子月水局无火偏旺限制规则',
    description:
      '壬水生子月，若地支成水局而丙丁全无，只能登记水势偏旺且缺少火暖的结构限制；润下是否成立须交由严格外格条件复核，不得从此处推断贫富层次。',
    months: ['子'],
    dayMasters: ['水'],
    dayStems: ['壬'],
    requiredFormationWuxings: ['水'],
    maxStemTotalCounts: { 丙: 0, 丁: 0 },
    usefulWuxing: '火',
    favorableOrder: ['火', '土'],
    traceHints: [
      '破格因素:支成水局而无丙丁',
      '结构限制:水势偏旺且缺火暖，不据此推断润下成败或贫富层次',
    ],
    hint: '壬水子月水局成势而无丙丁，列水旺缺暖限制',
  },
  {
    id: 'zi-month-ren-fire-formation-wu',
    label: '壬日子月火局戊透富贵规则',
    description:
      '壬水生子月，若地支成火局而戊土透干，水火既济、财官有根，较合原文"支成火局，有戊出干，富贵双全"。',
    months: ['子'],
    dayMasters: ['水'],
    dayStems: ['壬'],
    requiredFormationWuxings: ['火'],
    requiredVisibleStems: ['戊'],
    usefulWuxing: '土',
    favorableOrder: ['土', '火'],
    traceHints: ['取用层次:支成火局而戊土出干', '成格层次:富贵双全'],
    hint: '壬水子月火局成势而戊透，多主富贵双全',
  },
];
