import type { ClimateRule } from '../../types';

export const REN_ZI_CLIMATE_RULES: ClimateRule[] = [
  {
    id: 'zi-month-ren-wu-bing',
    label: '壬日子月戊丙并用规则',
    description: '壬水生子月，阳刃帮身，先取戊土，次用丙火。',
    priority: 118,
    months: ['子'],
    dayMasters: ['水'],
    dayStems: ['壬'],
    usefulWuxing: '土',
    favorableOrder: ['土', '火'],
    hint: '壬水子月，先取戊土，次用丙火',
  },
  {
    id: 'zi-month-ren-wu-bing-visible',
    label: '壬日子月戊丙两透富贵规则',
    description: '壬水生子月，戊丙两透，富贵荣华。',
    priority: 124,
    months: ['子'],
    dayMasters: ['水'],
    dayStems: ['壬'],
    requiredVisibleStems: ['戊', '丙'],
    usefulWuxing: '土',
    favorableOrder: ['土', '火'],
    traceHints: ['取用层次:戊丙两透', '成格层次:富贵荣华'],
    hint: '壬水子月戊丙两透，富贵荣华',
  },
  {
    id: 'zi-month-ren-wu-no-bing',
    label: '壬日子月有戊无丙略富规则',
    description: '壬水生子月，有戊无丙，略可言富。',
    priority: 122,
    months: ['子'],
    dayMasters: ['水'],
    dayStems: ['壬'],
    requiredVisibleStems: ['戊'],
    maxStemTotalCounts: { 丙: 0 },
    usefulWuxing: '土',
    favorableOrder: ['土', '火'],
    traceHints: ['取用层次:有戊无丙', '成格层次:略可言富'],
    hint: '壬水子月有戊无丙，略可言富',
  },
  {
    id: 'zi-month-ren-bing-no-wu',
    label: '壬日子月有丙无戊好谋无成规则',
    description: '壬水生子月，有丙无戊，好谋无成。',
    priority: 122,
    months: ['子'],
    dayMasters: ['水'],
    dayStems: ['壬'],
    requiredVisibleStems: ['丙'],
    maxStemTotalCounts: { 戊: 0 },
    usefulWuxing: '土',
    favorableOrder: ['土', '火'],
    traceHints: ['取用层次:有丙无戊', '成格层次:好谋无成'],
    hint: '壬水子月有丙无戊，好谋无成',
  },
  {
    id: 'zi-month-ren-water-formation-no-fire',
    label: '壬日子月水局丙不透庸人规则',
    description: '壬水生子月，支成水局而丙不出干，即有戊土，亦是庸人。',
    priority: 123,
    months: ['子'],
    dayMasters: ['水'],
    dayStems: ['壬'],
    requiredFormationWuxings: ['水'],
    maxVisibleStemCounts: { 丙: 0 },
    usefulWuxing: '土',
    favorableOrder: ['土', '火'],
    traceHints: ['破格因素:支成水局而丙不透', '成格层次:庸人'],
    hint: '壬水子月支成水局而丙不透，多作庸人',
  },
  {
    id: 'zi-month-ren-fire-formation-wealth',
    label: '壬日子月支成火局富裕规则',
    description: '壬水生子月，支成火局，一富而已。',
    priority: 121,
    months: ['子'],
    dayMasters: ['水'],
    dayStems: ['壬'],
    requiredFormationWuxings: ['火'],
    usefulWuxing: '火',
    favorableOrder: ['火', '土'],
    traceHints: ['取用层次:支成火局', '成格层次:一富而已'],
    hint: '壬水子月支成火局，一富而已',
  },
];
