/**
 * @file 命录百科全书词典库 (Minglu Glossary & Metaphysics Encyclopedia)
 * @description 汇集传统命理（八字、紫微、占星、风水、干支五行神煞）核心概念的释义与可核对的典籍摘录。
 */

import type { MingluGlossaryEntry } from './types';

export const MINGLU_GLOSSARY_DATABASE: MingluGlossaryEntry[] = [
  // 一、天干地支
  {
    term: '甲木',
    category: '干支',
    pinyin: 'jiǎ mù',
    shortDesc: '阳木，位居十干之首，常取参天大木之象。',
    fullDesc:
      '甲为阳木。《滴天髓》以参天之木为喻，指出旺木得火而敷荣；春秋取用分别随原局气势而变。',
    classicSource: '《滴天髓·天干论·甲木》：“甲木参天，脱胎要火。”',
    anchorId: 'glossary-jia-mu',
    relatedTerms: ['乙木', '阳木', '天干五合', '仁'],
  },
  {
    term: '乙木',
    category: '干支',
    pinyin: 'yǐ mù',
    shortDesc: '阴木，象征花草藤萝、枝叶柔木。',
    fullDesc: '乙为阴木，古籍以柔木、藤萝为喻。《滴天髓》分别讨论得丙丁、系甲木及虚湿之地等组合。',
    classicSource: '《滴天髓·天干论·乙木》：“乙木虽柔，刲羊解牛。”',
    anchorId: 'glossary-yi-mu',
    relatedTerms: ['甲木', '藤萝系甲', '阴木'],
  },
  {
    term: '丙火',
    category: '干支',
    pinyin: 'bǐng huǒ',
    shortDesc: '阳火，传统常以烈火、日光取象。',
    fullDesc:
      '丙为阳火。《滴天髓》以猛烈之火论其与庚辛金、旺水及木火之势的不同关系；具体强弱和取用仍看组合。',
    classicSource: '《滴天髓·天干论·丙火》：“丙火猛烈，欺霜侮雪。”',
    anchorId: 'glossary-bing-huo',
    relatedTerms: ['丁火', '壬水', '水火既济', '礼'],
  },
  {
    term: '丁火',
    category: '干支',
    pinyin: 'dīng huǒ',
    shortDesc: '阴火，古籍取柔中有明之象。',
    fullDesc: '丁为阴火。《滴天髓》取柔中有明之象，并以秋冬得甲木为条件讨论其生扶。',
    classicSource: '《滴天髓·天干论·丁火》：“丁火柔中，内性昭融。”',
    anchorId: 'glossary-ding-huo',
    relatedTerms: ['丙火', '阴火', '文明'],
  },
  {
    term: '戊土',
    category: '干支',
    pinyin: 'wù tǔ',
    shortDesc: '阳土，传统常取山冈厚土之象。',
    fullDesc: '戊为阳土。《滴天髓》以固重、喜润恶燥论其气象，并指出坐寅或申时冲动根气的条件。',
    classicSource: '《滴天髓·天干论·戊土》：“戊土固重，既中且正。”',
    anchorId: 'glossary-wu-tu',
    relatedTerms: ['己土', '厚德载物', '信'],
  },
  {
    term: '己土',
    category: '干支',
    pinyin: 'jǐ tǔ',
    shortDesc: '阴土，古籍取卑湿蓄藏之象。',
    fullDesc:
      '己为阴土，古籍以田园湿土取象。《滴天髓》论其蓄藏与生木、纳水的关系，火金多少也有不同条件。',
    classicSource: '《滴天髓·天干论·己土》：“己土卑湿，中正蓄藏。”',
    anchorId: 'glossary-ji-tu',
    relatedTerms: ['戊土', '田园之土'],
  },
  {
    term: '庚金',
    category: '干支',
    pinyin: 'gēng jīn',
    shortDesc: '阳金，古籍取刚强带煞之象。',
    fullDesc: '庚为阳金。《滴天髓》以刚强带煞为喻，分别讨论得水、得火及土之燥湿的影响。',
    classicSource: '《滴天髓·天干论·庚金》：“庚金带煞，刚强为最。”',
    anchorId: 'glossary-geng-jin',
    relatedTerms: ['辛金', '丁火', '义'],
  },
  {
    term: '辛金',
    category: '干支',
    pinyin: 'xīn jīn',
    shortDesc: '阴金，古籍取温润清柔之象。',
    fullDesc: '辛为阴金。《滴天髓》取温润清柔之象，论及厚土埋金、水多秀金与寒热配合。',
    classicSource: '《滴天髓·天干论·辛金》：“辛金软弱，温润而清。”',
    anchorId: 'glossary-xin-jin',
    relatedTerms: ['庚金', '壬水淘洗'],
  },
  {
    term: '壬水',
    category: '干支',
    pinyin: 'rén shuǐ',
    shortDesc: '阳水，古籍取汪洋周流之象。',
    fullDesc: '壬为阳水。《滴天髓》以汪洋周流论之，同时分别讨论通根、透癸、从化等情形。',
    classicSource: '《滴天髓·天干论·壬水》：“壬水汪洋，能泄金气。”',
    anchorId: 'glossary-ren-shui',
    relatedTerms: ['癸水', '戊土防洪', '智'],
  },
  {
    term: '癸水',
    category: '干支',
    pinyin: 'guǐ shuǐ',
    shortDesc: '阴水，古籍取至弱而能化之象。',
    fullDesc: '癸为阴水。《滴天髓》以至弱、通达作比喻，后文论及合戊见火等化气条件。',
    classicSource: '《滴天髓·天干论·癸水》：“癸水至弱，达于天津。”',
    anchorId: 'glossary-gui-shui',
    relatedTerms: ['壬水', '雨露之水'],
  },

  // 二、十神体系
  {
    term: '正官',
    category: '十神',
    pinyin: 'zhèng guān',
    shortDesc: '克我而阴阳相配者，常用来表示约束、规范与职分。',
    fullDesc: '正官是克制日主且阴阳相配的十神。正官格重视财印相辅，以及伤官克官、官杀混杂等条件。',
    classicSource: '《子平真诠·论正官》：“官以克身，虽与七煞有别，终受彼制。”',
    anchorId: 'glossary-zheng-guan',
    relatedTerms: ['七杀', '官印相生', '伤官见官'],
  },
  {
    term: '七杀',
    category: '十神',
    pinyin: 'qī shā',
    shortDesc: '克我而阴阳同性者，亦称偏官，取象于制约与压力。',
    fullDesc: '七杀又称偏官。其格局作用随日主强弱、制杀及化杀等配合而变。',
    classicSource: '《渊海子平·论七杀》：“夫七杀者，亦名偏官。”',
    anchorId: 'glossary-qi-sha',
    relatedTerms: ['食神制杀', '杀印相生', '羊刃驾杀'],
  },
  {
    term: '正印',
    category: '十神',
    pinyin: 'zhèng yìn',
    shortDesc: '生我而阴阳相配者，常取庇护、学识与资助之象。',
    fullDesc: '正印是生扶日主且阴阳相配的十神。印格须看印的根气、官星生印及财星坏印等配合。',
    classicSource: '《三命通会·卷六·论印绶》：“印绶者，乃五行生我之名。”',
    anchorId: 'glossary-zheng-yin',
    relatedTerms: ['偏印', '财星破印', '官印相生'],
  },
  {
    term: '偏印',
    category: '十神',
    pinyin: 'piān yìn',
    shortDesc: '生我而阴阳同性者，亦称枭神，取象于偏向性的生扶。',
    fullDesc:
      '偏印与正印同属生我之神，阴阳关系不同。原典所论“倒食”着重偏印克制食神、影响食神生财的配合。',
    classicSource: '《渊海子平·论倒食》：“用食神亦忌见之。”',
    anchorId: 'glossary-pian-yin',
    relatedTerms: ['枭神夺食', '直觉与偏门智慧'],
  },
  {
    term: '正财',
    category: '十神',
    pinyin: 'zhèng cái',
    shortDesc: '我克而阴阳相配者，属财星，取象于可支配的资源。',
    fullDesc:
      '正财是日主所克且阴阳相配的十神。财格论中须看日主能否任财、食伤生财、比劫争财及财生官等条件。',
    classicSource: '《子平真诠·论财》：“财为我克，使用之物也，以能生官，所以为美。”',
    anchorId: 'glossary-zheng-cai',
    relatedTerms: ['偏财', '比劫夺财', '食伤生财'],
  },
  {
    term: '偏财',
    category: '十神',
    pinyin: 'piān cái',
    shortDesc: '我克而阴阳同性者，属财星，传统称为众人之财。',
    fullDesc:
      '偏财是日主所克且阴阳同性的十神。传统将其与共享、流动的财源相联系，格局作用随财星旺衰、比劫及食伤等配置而变。',
    classicSource: '《渊海子平·论偏财》：“偏财者，乃众人之财也。”',
    anchorId: 'glossary-pian-cai',
    relatedTerms: ['正财', '偏财格', '商机运作'],
  },
  {
    term: '食神',
    category: '十神',
    pinyin: 'shí shén',
    shortDesc: '我生而阴阳同性者，属食伤，取象于日主的输出与生发。',
    fullDesc: '食神是日主所生且阴阳同性的十神。格局中可考察食神生财、食神制杀及偏印克食等组合。',
    classicSource: '《三命通会·卷六·论食神》：“食神一名寿星，一名爵星。”',
    anchorId: 'glossary-shi-shen',
    relatedTerms: ['食神生财', '食神制杀', '寿星'],
  },
  {
    term: '伤官',
    category: '十神',
    pinyin: 'shāng guān',
    shortDesc: '我生而阴阳相配者，属食伤，取象于日主的输出与表达。',
    fullDesc: '伤官是日主所生且阴阳相配的十神。伤官格须分辨见官、用财、配印等不同条件。',
    classicSource: '《渊海子平·论伤官》：“伤官者，我生彼之谓也；以阳见阴，阴见阳。”',
    anchorId: 'glossary-shang-guan',
    relatedTerms: ['伤官见官', '伤官配印', '伤官生财'],
  },
  {
    term: '比肩',
    category: '十神',
    pinyin: 'bǐ jiān',
    shortDesc: '与日主五行相同、阴阳同性者，属比劫。',
    fullDesc:
      '比肩与日主五行和阴阳属性均相同。传统格局论将其视作同类帮身或争财的一种因素，具体作用取决于日主强弱及财官配置。',
    anchorId: 'glossary-bi-jian',
    relatedTerms: ['劫财', '比劫帮身', '同侪竞争'],
  },
  {
    term: '劫财',
    category: '十神',
    pinyin: 'jié cái',
    shortDesc: '与日主五行相同、阴阳相配者，属比劫。',
    fullDesc:
      '劫财与日主五行相同而阴阳相配。传统论法既讨论同类帮身，也讨论争财，其作用随日主强弱和财星配置而变。',
    classicSource: '《渊海子平·论劫财》：“如乙见甲为劫财。”',
    anchorId: 'glossary-jie-cai',
    relatedTerms: ['比肩', '羊刃', '比劫夺财'],
  },

  // 三、神煞与吉凶
  {
    term: '天乙贵人',
    category: '神煞',
    pinyin: 'tiān yǐ guì rén',
    shortDesc: '八字神煞之一，传统取贵人扶助之象。',
    fullDesc: '天乙贵人按天干查相应地支，是传统八字神煞的贵人取象；具体解读结合四柱格局。',
    anchorId: 'glossary-tian-yi-gui-ren',
    relatedTerms: ['太极贵人', '天德贵人', '吉神'],
  },
  {
    term: '文昌贵人',
    category: '神煞',
    pinyin: 'wén chāng guì rén',
    shortDesc: '八字神煞之一，传统取文思与学业之象。',
    fullDesc:
      '文昌贵人按天干与地支关系查取，常用于文思、学业方面的传统取象；此条属于八字神煞体系。',
    anchorId: 'glossary-wen-chang-gui-ren',
    relatedTerms: ['学堂词馆', '食神', '科名'],
  },
  {
    term: '驿马',
    category: '神煞',
    pinyin: 'yì mǎ',
    shortDesc: '八字神煞之一，传统取行旅、迁动之象。',
    fullDesc:
      '驿马按三合局与所冲地支查取，传统用作行旅、迁动的象征；解读结合所临十神、旺衰与四柱关系。',
    anchorId: 'glossary-yi-ma',
    relatedTerms: ['禄马交驰', '财禄夹马', '迁移'],
  },
  {
    term: '华盖',
    category: '神煞',
    pinyin: 'huá gài',
    shortDesc: '八字神煞之一，传统取清静、专注之象。',
    fullDesc: '华盖按三合局墓库地支查取，因宝盖之象常与清静、宗教或艺术联系。',
    anchorId: 'glossary-hua-gai',
    relatedTerms: ['孤辰寡宿', '艺术灵性'],
  },
  {
    term: '羊刃',
    category: '神煞',
    pinyin: 'yáng rèn',
    shortDesc: '八字神煞之一，传统取刚强、竞争之象。',
    fullDesc:
      '阳刃古法以五阳干取刃：甲卯、丙戊午、庚酉、壬子；另有神煞查法兼取阴干刃位。格局论结合七杀、印绶及日主强弱等配合。',
    classicSource: '《渊海子平·论阳刃》：“如命中有刃，不可便言凶。”',
    anchorId: 'glossary-yang-ren',
    relatedTerms: ['七杀', '羊刃驾杀', '帝旺'],
  },
  {
    term: '咸池（桃花）',
    category: '神煞',
    pinyin: 'xián chí',
    shortDesc: '八字神煞之一，又称桃花，传统取情感与交际之象。',
    fullDesc: '咸池又称桃花，按三合局及沐浴之地等传统关系查取。古法将其与情感、交际联系。',
    anchorId: 'glossary-xian-chi',
    relatedTerms: ['红鸾天喜', '沐浴', '艺术人缘'],
  },

  // 四、紫微斗数核心
  {
    term: '紫微星',
    category: '星曜',
    pinyin: 'zǐ wēi xīng',
    shortDesc: '紫微斗数主星，属土，古籍称中天尊星、帝座。',
    fullDesc: '紫微星在传统斗数中取帝座之象。古籍重视其庙旺及辅弼、昌曲等会照条件。',
    classicSource: '《紫微斗数全书·卷一·问紫微所主若何》：“紫微属土，乃中天之尊星为帝座。”',
    anchorId: 'glossary-zi-wei-xing',
    relatedTerms: ['天府星', '君臣庆会', '北斗星系'],
  },
  {
    term: '天府星',
    category: '星曜',
    pinyin: 'tiān fǔ xīng',
    shortDesc: '紫微斗数南斗主星，属土，传统取财库之象。',
    fullDesc:
      '天府星在斗数中属南斗，古籍将其与财帛、田宅、衣禄相联系，同时讨论会吉、受煞及所居宫位等条件。',
    classicSource: '《紫微斗数全书·卷一·问天府所主若何》：“天府属土，南斗主令第一星也。”',
    anchorId: 'glossary-tian-fu-xing',
    relatedTerms: ['紫微星', '府相朝垣', '南斗星系'],
  },
  {
    term: '生年四化',
    category: '格局',
    pinyin: 'shēng nián sì huà',
    shortDesc: '紫微斗数依出生年干所定的化禄、化权、化科、化忌。',
    fullDesc:
      '生年四化由年干确定四类化曜，传统以化禄、化权、化科、化忌描述星曜作用的变化。解读结合实际化曜、落宫及会照。',
    anchorId: 'glossary-sheng-nian-si-hua',
    relatedTerms: ['化禄', '化权', '化科', '化忌'],
  },
  {
    term: '三方四正',
    category: '宫位',
    pinyin: 'sān fāng sì zhèng',
    shortDesc: '斗数中本宫、两处三合宫与对宫的合参范围。',
    fullDesc:
      '以某宫为本宫，连同两处三合宫和相对的对宫，合称三方四正。斗数中合参这些宫位的星曜及四化。',
    anchorId: 'glossary-san-fang-si-zheng',
    relatedTerms: ['对宫', '三合宫', '宫位会照'],
  },

  // 五、占星与风水
  {
    term: '上升星座',
    category: '占星',
    pinyin: 'shàng shēng xīng zuò',
    shortDesc: '出生时东方地平线与黄道的交点，其黄道位置对应上升星座。',
    fullDesc:
      '上升点（Ascendant）是黄道与当地东方地平线的交点；其黄经落入的黄道十二宫区段称为上升星座。占星中常用于自我呈现的象征。象限分宫制多以上升点为第一宫宫头；整宫制以其所在区段的起点为第一宫宫头。',
    anchorId: 'glossary-ascendant',
    relatedTerms: ['天顶MC', '太阳星座', '月亮星座'],
  },
  {
    term: '天顶',
    category: '占星',
    pinyin: 'tiān dǐng',
    shortDesc: '黄道与当地子午圈的上中天交点，常用于职业取象。',
    fullDesc:
      '天顶（Midheaven / Medium Coeli，MC）是黄道与当地子午圈的上中天交点，占星中常联系职业和公共角色。在普拉西德等象限分宫制中通常为第十宫宫头；整宫制中，天顶可能落在其他宫内。',
    anchorId: 'glossary-midheaven',
    relatedTerms: ['上升点ASC', '第十宫', '职业成就'],
  },
  {
    term: '八宅游年',
    category: '风水',
    pinyin: 'bā zhái yóu nián',
    shortDesc: '八宅风水中按宅卦推算八方游星的传统方法。',
    fullDesc:
      '八宅游年依宅卦推算生气、延年、天医、伏位、绝命、五鬼、六煞、祸害八种游星方位。传统将其分为四吉、四凶，用于宅内方位分析。',
    anchorId: 'glossary-ba-zhai-you-nian',
    relatedTerms: ['本命卦', '生气', '延年', '天医', '伏位'],
  },
];
