/**
 * 调候规则只采用明确的首条命中顺序，不把顺序解释为传统强弱分数。
 * 同一命局同时满足多条条件时，例外条件列在常规条件之前；新增规则必须显式加入本表。
 */
export const CLIMATE_RULE_PRECEDENCE = `
  you-month-xin-wuzi-chaoyang-authority you-month-xin-wuzi-chaoyang you-month-xin-three-xin-single-ren-many-jia-geng-ding-refined you-month-xin-three-xin-single-ren-many-jia-geng-rich
  chou-month-gui-gui-ji-party-night-ding you-month-bing-metal-formation-no-xin you-month-bing-metal-formation-xin-follow-wealth you-month-ding-xin-follow-wealth
  zi-month-ding-follow-kill-broken-by-companion wei-month-gui-ding-break-metal chou-month-gui-gui-ji-party-no-ding mao-month-jia-bing-gui-wu-all
  shen-month-jia-bing-gui-geng-all xu-month-jia-bing-gui-geng-all hai-month-jia-bing-gui-geng-all zi-month-jia-bing-gui-geng-all
  chou-month-jia-bing-gui-geng-all si-month-yi-bing-gui-geng-all wei-month-yi-gui-bing-geng-all shen-month-yi-bing-gui-geng-all
  xu-month-yi-bing-gui-geng-all hai-month-yi-bing-gui-geng-all zi-month-yi-bing-gui-xin-all shen-month-bing-wu-xin-geng-all
  you-month-bing-wu-heavy-false-scholar hai-month-bing-wu-xin-geng-all zi-month-bing-wu-xin-geng-all chou-month-bing-wu-xin-geng-all
  si-month-ding-geng-jia-ren-all wei-month-ding-geng-jia-ren-all shen-month-ding-geng-jia-ren-all xu-month-ding-geng-jia-ren-all
  hai-month-ding-geng-jia-ren-all zi-month-ding-follow-kill-water-prosper yin-month-wu-bing-jia-geng-all mao-month-wu-bing-jia-geng-all
  chen-month-wu-officer-party-geng si-month-wu-gui-bing-xin-all wu-month-wu-gui-bing-xin-all hai-month-wu-bing-jia-geng-all
  zi-month-wu-bing-jia-geng-all chou-month-wu-bing-jia-geng-all yin-month-ji-bing-jia-geng-all si-month-ji-gui-bing-xin-all
  wu-month-ji-gui-bing-xin-all shen-month-ji-bing-jia-geng-all xu-month-ji-bing-jia-geng-all hai-month-ji-bing-jia-geng-all
  zi-month-ji-bing-jia-geng-all chou-month-ji-bing-jia-geng-all si-month-geng-bing-ren-jia-all zi-month-geng-bing-ding-all
  chen-month-xin-double-bing-with-gui-scholarly chen-month-xin-fire-many-with-gui-relief chen-month-xin-companions-heavy-water-weak-jia-noble you-month-xin-metal-formation-ren-high
  mao-month-xin-ren-flood-with-wu-auspicious mao-month-xin-ren-bing-all-great-wealth si-month-ren-bing-jia-xin-all
  shen-month-ren-wu-ding-jia-all you-month-ren-bing-jia-geng-all xu-month-ren-bing-jia-xin-all si-month-gui-bing-xin-geng-all
  wu-month-gui-ji-pure-follow-kill wei-month-gui-xiaoshu-metal-water-rich shen-month-gui-bing-xin-geng-all xu-month-gui-bing-xin-geng-all
  hai-month-gui-bing-xin-geng-all chou-month-gui-water-formation-no-bing you-month-bing-one-ren-rich chen-month-wu-officer-party-no-geng
  shen-month-wu-no-bing-no-gui-no-jia wu-month-geng-bing-ren-jia-all wei-month-geng-jia-gui-all chen-month-xin-double-bing-argue-combine
  chen-month-xin-four-storage-no-jia-dull chen-month-xin-fire-many-no-water-monastic chen-month-xin-companions-heavy-water-weak-early-loss si-month-xin-metal-formation-water-wood-clarity
  wei-month-xin-zi-ren-jia-ordinary shen-month-xin-metal-rich-ren-jia-single-wu you-month-xin-white-tiger you-month-xin-ji-with-geng-jia-hidden-leisure
  you-month-xin-water-flood-hidden-wu-artistry you-month-xin-yi-wood-with-geng yin-month-xin-fire-formation-ren-only-ordinary yin-month-xin-fire-formation-geng-ren-all-distinguished
  yin-month-xin-water-formation-no-bing-ordinary yin-month-xin-water-formation-bing-visible-rich mao-month-xin-ren-flood-no-wu-meager mao-month-xin-wood-formation-with-geng-rich
  mao-month-xin-wood-formation-no-geng-ordinary mao-month-xin-fire-formation-double-ren-marvel wu-month-gui-fire-formation-two-ren-one-geng wei-month-gui-dashu-metal-rich
  chou-month-gui-fire-formation-metal-support mao-month-xin-fire-formation-base-low mao-month-xin-pure-ren-no-bing-prominent wu-month-jia-no-gui-use-ding
  wu-month-yi-mangzhong-metal-water-fire-first wu-month-bing-ding-ren-he you-month-bing-hidden-ren-xiucai xu-month-bing-geng-wu-trap-jia-ren
  xu-month-bing-no-jia-no-ren-no-gui chen-month-wu-follow-kill shen-month-wu-bing-gui-jia-all you-month-wu-no-bing-no-gui
  mao-month-ji-follow-kill-no-resource chen-month-xin-hai-zi-land-with-shen-rank chen-month-xin-wu-control-water-no-jia-yi-leisure si-month-xin-ren-hai-hidden-no-wu
  si-month-xin-ren-hai-jia-visible wu-month-xin-ren-ji-visible-hidden-gui wu-month-xin-fire-formation-ren-break-fire wei-month-xin-ding-yi-with-ren-geng
  wei-month-xin-single-ren-single-ji-geng-no-jia shen-month-xin-ren-in-shen-no-extra-wu shen-month-xin-water-rich-wu-supported-longevity you-month-xin-pure-xin-single-ren
  you-month-xin-ren-many-jia-with-geng you-month-xin-soil-bury-metal-with-jia you-month-xin-metal-formation-no-ren-with-ding you-month-xin-metal-formation-no-ren-no-ding
  you-month-xin-white-tiger-with-fire-ordinary you-month-xin-pure-ji-monastic you-month-xin-water-flood-no-wu you-month-xin-yi-wood-no-geng-ren
  xu-month-xin-wood-earth-double-gui-rich-hardship xu-month-xin-many-ji-gui-no-ren-cloudy-rich hai-month-xin-ren-bing-all zi-month-xin-ren-bing-all-no-wu-gui
  chou-month-xin-bing-ren-all yin-month-xin-ji-ren-visible-geng-hidden-jia-control mao-month-xin-ren-jia-all-noble mao-month-xin-ren-wu-with-yi-scholarly-false
  yin-month-ren-bing-geng-jia zi-month-ren-fire-formation-wu wu-month-gui-metal-no-visible-water-single-water-rich chou-month-gui-fire-formation-no-metal
  wu-month-yi-xiazhi-bing-gui yin-month-bing-double-geng-no-xin wei-month-bing-geng-ren-kejia you-month-bing-ding-xin-cunning
  xu-month-bing-hidden-jia-ren-no-geng xu-month-bing-jia-ren-all yin-month-ding-jia-geng-all wu-month-ding-geng-ren-tu-ordinary
  yin-mao-month-wu-no-geng-no-resource-follow-kill-fail shen-month-wu-gui-jia-no-bing you-month-wu-bing-gui-all yin-month-geng-wu-xin-ji
  mao-month-geng-wood-formation-ding shen-month-geng-jia-ding-all chen-month-xin-ren-jia-all si-month-xin-gui-visible-ren-hidden
  si-month-xin-ren-hai-hidden-with-wu si-month-xin-ren-gui-hidden-wu-ji-hidden si-month-xin-fire-formation-water-control si-month-xin-fire-formation-no-water-earth
  wu-month-xin-ren-visible-ji-hidden-gui-page wu-month-xin-gui-geng-no-ren-grace wu-month-xin-no-ren-gui-wu-with-companion wu-month-xin-fire-formation-gui-heavy-no-ren
  wei-month-xin-ding-yi-no-ren-fails wei-month-xin-ren-geng-no-wu wei-month-xin-wu-visible-no-jia-break wei-month-xin-wu-jia-geng-break
  wei-month-xin-wu-jia-adjacent-ji shen-month-xin-earth-with-jia you-month-xin-ren-many-jia-no-geng you-month-xin-soil-bury-metal-no-jia
  xu-month-xin-ren-jia-all xu-month-xin-wood-many-earth-thick-no-water-ordinary xu-month-xin-ji-visible-gui-no-ren-scholarly xu-month-xin-no-ren-jia-bing-xin-with-chen-glory
  hai-month-xin-bing-visible-ren-hidden hai-month-xin-ren-visible-bing-hidden hai-month-xin-wu-many-ren-few-fame hai-month-xin-ji-many-with-wu-honest
  zi-month-xin-ren-hidden-bing-visible zi-month-xin-ren-many-with-wu-bing-jia zi-month-xin-water-formation-gui-two-wu zi-month-xin-run-down-prosper
  chou-month-xin-bing-ren-hidden chou-month-xin-many-bing-no-ren-gui-trade yin-month-xin-ji-visible-jia-hidden-alt-grace mao-month-xin-ren-sits-hai-no-earth-well-off
  mao-month-xin-shen-hidden-ren-alt-fame mao-month-xin-ren-wu-visible-no-jia-ordinary mao-month-ren-bing-jia-all wu-month-ren-bing-xin-all
  wei-month-ren-fire-formation-jia zi-month-ren-water-formation-no-fire chou-month-ren-dahan-bing-jia chen-month-gui-guyu-bing-xin-jia
  wu-wei-month-gui-metal-water-summer-rich wu-month-gui-fire-formation-no-ren-monastic yin-month-xin-ren-visible-geng-no-ji-incomplete you-month-yi-qiufen-bing-no-gui
  yin-month-bing-geng-xin-mixed si-month-bing-no-ren-gui-geng wu-month-bing-ren-geng-tu-misc you-month-bing-xin-poor
  xu-month-bing-hidden-ren-gui-page xu-month-bing-jia-gui-no-ren mao-month-ding-geng-yi-greedy-combine wu-month-ding-geng-ren-kejia
  mao-month-geng-ding-only mao-month-geng-water-formation-wu chen-month-geng-jia-no-bing chen-month-geng-water-formation-wu
  si-month-geng-jia-bing-first wu-month-geng-bing-jia-first chen-month-xin-ren-visible-jia-hidden si-month-xin-no-ren-gui-fire-lonely
  wu-month-xin-no-ren-gui-wu-monastic wu-month-xin-no-ren-gui-weak-substitute wei-month-xin-wu-jia-separated wei-month-xin-ren-geng-hidden-glory
  wei-month-xin-wood-formation-ren-visible-geng-total shen-month-xin-earth-no-jia you-month-xin-ren-jia-single-no-geng xu-month-xin-jia-visible-ren-hidden
  xu-month-xin-no-ren-jia-bing-xin-slight-noble hai-month-xin-ren-bing-hidden hai-month-xin-wu-ren-storage hai-month-xin-jia-many-wu-few-art
  hai-month-xin-water-many-no-wu-bing zi-month-xin-gui-visible-bing-visible-no-ren zi-month-xin-ren-many-jia-yi-heavy-no-bing zi-month-xin-water-formation-gui-no-wu
  zi-month-xin-run-down-no-metal-monastic zi-month-xin-wood-formation-ding-wu-merit chou-month-xin-bing-only-no-ren chou-month-xin-ren-only-no-bing
  chou-month-xin-water-many-earth-fire-peace yin-month-xin-ren-visible-no-ji-geng-poor mao-month-xin-no-ren-ordinary chen-month-ren-jia-no-geng
  chen-month-ren-water-formation-wu wei-month-ren-jia-no-xin hai-month-ren-wu-no-bing hai-month-ren-wood-formation-wu
  zi-month-ren-wu-no-bing zi-month-ren-bing-no-wu chou-month-ren-xiaohan-bing-only chen-month-gui-qingming-bing-only
  wu-month-gui-metal-stem-water-formation mao-month-geng-water-formation-no-wu yin-month-xin-bing-visible-martial si-month-jia-gui-ding-geng
  hai-month-jia-bing-gui-first zi-month-jia-bing-gui-first chou-month-jia-bing-gui-first si-month-yi-bing-gui-first
  you-month-yi-qiufen-gui-no-bing hai-month-yi-bing-gui-first zi-month-yi-bing-gui-first chou-month-yi-bing-only
  chen-month-bing-jia-no-ren si-month-bing-no-ren-use-gui wu-month-bing-no-ren-use-gui wei-month-bing-ji-mixed-vulgar
  you-month-bing-no-ren-use-gui hai-month-bing-wu-xin-first zi-month-bing-wu-xin-first chou-month-bing-wu-xin-first
  wu-month-ding-gui-unique-kill wei-month-wu-gui-jia-no-bing shen-month-wu-no-gui-no-jia chou-month-wu-bing-jia-first
  si-wu-wei-month-ji-no-gui-ren-allowed yin-month-geng-wood-fire-both mao-month-geng-no-fire-ordinary chen-month-geng-no-jia-bing
  si-month-geng-bing-first-jia-assist wei-month-geng-bing-jia-first hai-month-geng-bing-jia-first zi-month-geng-bing-first
  chou-month-geng-bing-first chen-month-xin-jia-visible-ren-hidden si-month-xin-jia-no-ren-gui wu-month-xin-no-ren-ji-visible-alt-path
  wu-month-xin-wood-fire-heavy-no-metal-water-warning shen-month-xin-gui-only-not-usable xu-month-xin-ren-visible-jia-hidden-with-wu hai-month-xin-ren-many-no-wu
  zi-month-xin-ren-many-no-wu-bing yin-month-ren-geng-bing-wu chen-month-ren-no-jia-geng wei-month-ren-no-jia-xin
  hai-month-ren-no-wu-bing zi-month-ren-no-wu-bing hai-month-gui-bing-xin-first mao-month-jia-bing-gui-first
  wu-month-jia-gui-ding-geng shen-month-jia-bing-gui-first you-month-jia-fire-forge xu-month-jia-bing-gui-first
  si-month-yi-bing-gui-second wei-month-yi-bing-gui-first shen-month-yi-bing-gui-first you-month-yi-bailu-ren-temporary
  xu-month-yi-bing-gui-first yin-month-bing-no-ren-use-gui mao-month-bing-no-ren-ji-temporary wu-month-bing-ren-no-geng
  wei-month-bing-ren-no-geng-no-wu wei-month-bing-ren-wu-no-geng shen-month-bing-wu-xin-first si-month-wu-gui-bing-first
  wu-month-wu-gui-bing-first wei-month-wu-gui-no-bing-no-jia xu-month-wu-jia-bing-gui hai-month-wu-bing-jia-first
  zi-month-wu-bing-jia-first si-month-ji-bing-gui-first wu-month-ji-gui-bing-first hai-month-ji-bing-jia-first
  zi-month-ji-bing-jia-first chou-month-ji-bing-jia-first yin-month-geng-jia-bing-xin si-month-geng-ren-bing
  shen-month-geng-jia-bing-first you-month-geng-jia-ding-first xu-month-geng-ding-jia-first chen-month-xin-no-ren-no-jia
  si-month-xin-no-ren-gui-jia wu-month-xin-water-earth-heavy-see-jia shen-month-xin-metal-many-shallow-water-balance xu-month-xin-heavy-earth-ren-visible-jia-hidden-rich
  yin-month-ren-geng-bing-first yin-month-ren-geng-first-bing-assist wu-month-ren-bing-first wei-month-ren-xin-jia-gui
  shen-month-ren-wu-ding-first xu-month-ren-bing-jia-first si-month-gui-bing-xin-first shen-month-gui-bing-xin-first
  xu-month-gui-bing-xin-first chen-month-jia-geng-first wei-month-jia-ding-geng chen-month-ding-geng-jia-first
  si-month-ding-geng-jia-first wei-month-ding-geng-jia-first shen-month-ding-geng-jia-first xu-month-ding-geng-jia-first
  hai-month-ding-geng-jia-first yin-month-wu-bing-jia-first mao-month-wu-bing-jia-first wei-month-wu-gui-bing-jia
  yin-month-ji-bing-jia-first mao-month-ji-bing-jia-first chen-month-ji-bing-jia-first shen-month-ji-bing-jia-first
  xu-month-ji-bing-jia-first yin-month-geng-jia-first yin-month-geng-bing-jia chen-month-geng-jia-bing
  wu-month-geng-ren-ding wei-month-geng-jia-ren shen-month-geng-ding-jia xu-month-geng-jia-ren
  zi-month-geng-bing-ding chou-month-geng-bing-jia shen-month-ren-wu-ding zi-month-gui-bing-xin
  yin-month-jia-bing-gui mao-month-yi-bing-gui chen-month-yi-gui-bing yin-month-ding-bing-jia-first
  mao-month-ding-jia-geng-first mao-month-geng-bing-ding you-month-geng-ding-jia hai-month-geng-bing-jia
  mao-month-ren-bing-first chen-month-ren-jia-geng wu-month-ren-gui-geng wei-month-ren-jia-xin-gui
  you-month-ren-jia-drain-soil xu-month-ren-jia-bing hai-month-ren-wu-bing zi-month-ren-wu-bing
  yin-month-yi-bing-gui mao-month-ren-wu-xin si-month-ren-water-self-support you-month-ren-jia-wu
  yin-month-gui-xin-bing you-month-gui-xin-bing zi-month-ding-jia-geng chou-month-ding-jia-geng
  you-month-ji-gui-bing mao-month-gui-geng-first winter-fire-wood-rescue si-month-ren-bing-jia-first
  you-month-ren-bing-jia-first winter-metal-fire-temper autumn-wood-water-moisten summer-metal-water-wash
  autumn-metal-water-polish spring-wood-fire-warm winter-earth-fire-thaw spring-earth-fire-dry
  summer-wood-fire-cool winter-water-wood-warm
`
  .trim()
  .split(/\s+/);
