/**
 * 无 policy 的旧调候条目逐条登记具体荐干或正面作用干。
 * 空数组表示该条只陈述五行方向或条件结果，不采用具体天干。
 */
export const CLIMATE_RULE_RECOMMENDATION_STEMS: Readonly<Record<string, readonly string[]>> = {
  'spring-wood-fire-warm': [],
  'spring-earth-fire-dry': [],
  'summer-wood-fire-cool': [],
  'winter-water-wood-warm': [],
  'winter-fire-wood-rescue': [],
  'winter-metal-fire-temper': [],
  'summer-metal-water-wash': [],
  'winter-earth-fire-thaw': [],
  'autumn-wood-water-moisten': [],
  'autumn-metal-water-polish': [],
  'yin-month-jia-bing-gui': ['丙', '癸'],
  'mao-month-jia-geng-wu-first': ['庚', '戊'],
  'chen-month-jia-geng-first': ['庚'],
  'si-month-jia-gui-ding-geng': ['癸', '丁', '庚'],
  'wu-month-jia-gui-ding-geng': ['癸', '丁', '庚'],
  'wu-month-jia-no-gui-use-ding': ['丁', '庚'],
  'shen-month-jia-bing-gui-first': ['丁', '庚'],
  'you-month-jia-fire-forge': ['丁'],
  'xu-month-jia-ding-gui-first': ['丁', '癸'],
  'hai-month-jia-bing-gui-first': ['庚', '丁', '丙'],
  'zi-month-jia-ding-geng-bing': ['丁', '庚', '丙'],
  'chou-month-jia-geng-ding-first': ['庚', '丁'],
  'yin-month-yi-bing-gui': ['丙', '癸'],
  'mao-month-yi-bing-gui': ['丙', '癸'],
  'chen-month-yi-gui-bing': ['癸', '丙'],
  'si-month-yi-bing-gui-first': ['癸', '丙'],
  'si-month-yi-bing-gui-second': ['癸', '丙'],
  'wu-month-yi-mangzhong-metal-water-fire-first': ['丙'],
  'wu-month-yi-xiazhi-bing-gui': ['丙', '癸'],
  'wei-month-yi-bing-gui-first': ['癸', '丙'],
  'shen-month-yi-bing-gui-first': ['丙', '癸'],
  'you-month-yi-qiufen-bing-no-gui': ['丙', '癸'],
  'you-month-yi-qiufen-gui-no-bing': [],
  'you-month-yi-bailu-ren-temporary': ['壬'],
  'xu-month-yi-gui-xin-first': ['癸', '辛'],
  'hai-month-yi-bing-gui-first': ['丙', '戊'],
  'zi-month-yi-bing-only': ['丙'],
  'chou-month-yi-bing-only': ['丙'],
  'yin-month-bing-ren-geng-first': ['壬', '庚'],
  'yin-month-bing-no-ren-use-gui': ['癸'],
  'yin-month-bing-double-geng-no-xin': [],
  'yin-month-bing-geng-xin-mixed': [],
  'mao-month-bing-ren-first': ['壬'],
  'mao-month-bing-no-ren-ji-temporary': ['己'],
  'chen-month-bing-ren-first': ['壬'],
  'chen-month-bing-jia-no-ren': [],
  'si-month-bing-no-ren-use-gui': ['癸'],
  'si-month-bing-no-ren-gui-geng': [],
  'wu-month-bing-no-ren-use-gui': ['癸'],
  'wu-month-bing-ren-no-geng': [],
  'wu-month-bing-ren-geng-tu-misc': [],
  'wu-month-bing-ding-ren-he': [],
  'wei-month-bing-geng-ren-kejia': [],
  'wei-month-bing-ren-no-geng-no-wu': [],
  'wei-month-bing-ren-wu-no-geng': [],
  'wei-month-bing-ji-mixed-vulgar': [],
  'shen-month-bing-wu-xin-first': ['壬'],
  'you-month-bing-ren-first': ['壬'],
  'you-month-bing-metal-formation-no-xin': [],
  'you-month-bing-metal-formation-xin-follow-wealth': [],
  'you-month-bing-wu-heavy-false-scholar': [],
  'you-month-bing-one-ren-rich': [],
  'you-month-bing-hidden-ren-xiucai': [],
  'you-month-bing-ding-xin-cunning': [],
  'you-month-bing-xin-poor': [],
  'you-month-bing-no-ren-use-gui': ['癸'],
  'xu-month-bing-jia-ren-first': ['甲', '壬'],
  'xu-month-bing-hidden-ren-gui-page': [],
  'xu-month-bing-geng-wu-trap-jia-ren': [],
  'xu-month-bing-hidden-jia-ren-no-geng': [],
  'xu-month-bing-jia-ren-all': [],
  'xu-month-bing-jia-gui-no-ren': [],
  'xu-month-bing-no-jia-no-ren-no-gui': [],
  'zi-month-bing-wu-xin-first': ['壬', '戊'],
  'zi-month-bing-ren-wu-both-visible': [],
  'chou-month-bing-wu-xin-first': ['壬'],
  'yin-month-ding-geng-chop-jia': ['庚'],
  'mao-month-ding-geng-yi-greedy-combine': [],
  'mao-month-ding-jia-geng-first': ['庚', '甲'],
  'chen-month-ding-jia-geng-first': ['甲', '庚'],
  'si-month-ding-geng-jia-first': ['甲', '庚'],
  'wu-month-ding-gui-unique-kill': [],
  'wu-month-ding-geng-ren-tu-ordinary': [],
  'wu-month-ding-geng-ren-kejia': [],
  'wei-month-ding-geng-jia-first': ['甲', '壬'],
  'shen-month-ding-geng-jia-first': ['甲', '庚'],
  'you-month-ding-jia-geng-bing': ['甲', '庚', '丙'],
  'you-month-ding-xin-follow-wealth': [],
  'xu-month-ding-geng-jia-first': ['甲', '庚'],
  'hai-month-ding-geng-jia-first': ['甲', '庚'],
  'zi-month-ding-follow-kill-broken-by-companion': [],
  'zi-month-ding-follow-kill-water-prosper': [],
  'zi-month-ding-jia-geng': ['甲', '庚'],
  'chou-month-ding-jia-geng': ['甲', '庚'],
  'yin-mao-month-wu-no-geng-no-resource-follow-kill-fail': [],
  'yin-month-wu-bing-jia-first': ['丙', '甲'],
  'mao-month-wu-bing-jia-first': ['丙', '甲'],
  'chen-month-wu-officer-party-geng': ['庚'],
  'chen-month-wu-officer-party-no-geng': [],
  'chen-month-wu-follow-kill': [],
  'si-month-wu-gui-bing-first': ['甲', '丙', '癸'],
  'wu-month-wu-gui-bing-first': ['壬', '甲'],
  'wu-month-wu-ren-jia-both-visible': [],
  'wei-month-wu-gui-bing-jia': ['癸', '丙', '甲'],
  'wei-month-wu-gui-jia-no-bing': [],
  'wei-month-wu-gui-no-bing-no-jia': [],
  'shen-month-wu-bing-gui-jia-first': ['丙', '癸', '甲'],
  'shen-month-wu-bing-gui-jia-all': [],
  'shen-month-wu-gui-jia-no-bing': ['癸', '甲'],
  'shen-month-wu-no-gui-no-jia': [],
  'shen-month-wu-no-bing-no-gui-no-jia': [],
  'you-month-wu-bing-gui-first': ['丙', '癸'],
  'you-month-wu-bing-gui-all': [],
  'you-month-wu-no-bing-no-gui': [],
  'xu-month-wu-jia-bing-gui': ['甲', '丙', '癸'],
  'hai-month-wu-bing-jia-first': ['甲', '丙'],
  'zi-month-wu-bing-jia-first': ['丙', '甲'],
  'chou-month-wu-bing-jia-first': ['丙', '甲'],
  'yin-month-ji-bing-jia-first': ['丙'],
  'mao-month-ji-follow-kill-no-resource': [],
  'mao-month-ji-jia-gui-first': ['甲', '癸'],
  'chen-month-ji-bing-gui-jia': ['丙', '癸', '甲'],
  'si-wu-wei-month-ji-no-gui-ren-allowed': ['壬'],
  'si-month-ji-bing-gui-first': ['癸', '丙'],
  'wu-month-ji-gui-bing-first': ['癸', '丙'],
  'wei-month-ji-gui-bing-first': ['癸', '丙'],
  'shen-month-ji-bing-jia-first': ['癸', '丙', '辛'],
  'you-month-ji-gui-bing': ['癸', '丙'],
  'xu-month-ji-gui-bing-jia': ['癸', '丙', '甲'],
  'hai-month-ji-bing-jia-first': ['丙', '甲'],
  'zi-month-ji-bing-jia-first': ['丙', '甲'],
  'chou-month-ji-bing-jia-first': ['丙', '甲'],
  'yin-month-geng-bing-jia-visible': [],
  'yin-month-geng-bing-jia-first': ['丙', '甲', '丁'],
  'mao-month-geng-ding-first': ['丁', '甲', '庚'],
  'mao-month-geng-ding-jia-visible-geng-hidden': [],
  'mao-month-geng-bing-without-ding': [],
  'chen-month-geng-jia-ding-first': ['甲', '丁'],
  'chen-month-geng-jia-ding-visible-no-peer': [],
  'chen-month-geng-jia-hidden-ding-visible': [],
  'si-month-geng-ren-wu-bing-first': ['壬', '戊', '丙'],
  'si-month-geng-ren-wu-bing-visible': [],
  'wu-month-geng-ren-first-gui-next': ['壬', '癸'],
  'wei-month-geng-ding-jia-first': ['丁', '甲'],
  'shen-month-geng-jia-bing-first': ['丁', '甲'],
  'shen-month-geng-ding-jia-visible': [],
  'you-month-geng-jia-ding-first': ['丁', '甲'],
  'you-month-geng-ding-jia': [],
  'xu-month-geng-jia-ren': ['甲', '壬'],
  'hai-month-geng-ding-bing-jia': ['丁', '丙', '甲'],
  'hai-month-geng-ding-jia-visible-no-water-formation': ['丁', '甲'],
  'zi-month-geng-ding-jia-visible-bing-hidden': [],
  'zi-month-geng-ding-jia-first': ['丁', '甲', '丙'],
  'chou-month-geng-bing-first': ['丙', '丁', '甲'],
  'yin-month-xin-ji-ren-first': ['己', '壬', '庚'],
  'mao-month-xin-ren-first': ['壬'],
  'chen-month-xin-ren-jia-first': ['壬', '甲'],
  'chen-month-xin-ren-jia-all': [],
  'chen-month-xin-ren-visible-jia-hidden': [],
  'chen-month-xin-jia-visible-ren-hidden': [],
  'chen-month-xin-no-ren-no-jia': [],
  'chen-month-xin-double-bing-with-gui-scholarly': ['癸'],
  'chen-month-xin-double-bing-argue-combine': [],
  'chen-month-xin-hai-zi-land-with-shen-rank': [],
  'chen-month-xin-wu-control-water-no-jia-yi-leisure': [],
  'chen-month-xin-four-storage-no-jia-dull': [],
  'chen-month-xin-fire-many-with-gui-relief': ['癸'],
  'chen-month-xin-fire-many-no-water-monastic': [],
  'chen-month-xin-companions-heavy-water-weak-jia-noble': ['甲'],
  'chen-month-xin-companions-heavy-water-weak-early-loss': [],
  'si-month-xin-metal-formation-water-wood-clarity': [],
  'si-month-xin-ren-hai-hidden-no-wu': [],
  'si-month-xin-gui-visible-ren-hidden': [],
  'si-month-xin-ren-hai-hidden-with-wu': [],
  'si-month-xin-ren-hai-jia-visible': [],
  'si-month-xin-ren-gui-hidden-wu-ji-hidden': [],
  'si-month-xin-fire-formation-water-control': [],
  'si-month-xin-fire-formation-no-water-earth': [],
  'si-month-xin-no-ren-gui-fire-lonely': [],
  'si-month-xin-jia-no-ren-gui': [],
  'si-month-xin-no-ren-gui-jia': [],
  'wu-month-xin-ren-ji-visible-hidden-gui': [],
  'wu-month-xin-ren-visible-ji-hidden-gui-page': [],
  'wu-month-xin-gui-geng-no-ren-grace': [],
  'wu-month-xin-no-ren-gui-wu-with-companion': [],
  'wu-month-xin-no-ren-gui-wu-monastic': [],
  'wu-month-xin-no-ren-ji-visible-alt-path': [],
  'wu-month-xin-no-ren-gui-weak-substitute': ['癸'],
  'wu-month-xin-fire-formation-ren-break-fire': ['壬'],
  'wu-month-xin-fire-formation-gui-heavy-no-ren': [],
  'wu-month-xin-water-earth-heavy-see-jia': ['甲'],
  'wu-month-xin-wood-fire-heavy-no-metal-water-warning': [],
  'wei-month-xin-ding-yi-with-ren-geng': [],
  'wei-month-xin-ding-yi-no-ren-fails': [],
  'wei-month-xin-zi-ren-jia-ordinary': [],
  'wei-month-xin-single-ren-single-ji-geng-no-jia': [],
  'wei-month-xin-ren-geng-no-wu': [],
  'wei-month-xin-wu-visible-no-jia-break': [],
  'wei-month-xin-wu-jia-geng-break': [],
  'wei-month-xin-wu-jia-adjacent-ji': [],
  'wei-month-xin-wu-jia-separated': ['甲'],
  'wei-month-xin-ren-geng-hidden-glory': [],
  'wei-month-xin-wood-formation-ren-visible-geng-total': [],
  'shen-month-xin-metal-rich-ren-jia-single-wu': ['壬', '甲'],
  'shen-month-xin-ren-in-shen-no-extra-wu': [],
  'shen-month-xin-water-rich-wu-supported-longevity': [],
  'shen-month-xin-earth-with-jia': ['甲'],
  'shen-month-xin-earth-no-jia': [],
  'shen-month-xin-gui-only-not-usable': ['甲', '戊'],
  'shen-month-xin-metal-many-shallow-water-balance': ['壬'],
  'you-month-xin-pure-xin-single-ren': ['壬'],
  'you-month-xin-ren-jia-single-no-geng': [],
  'you-month-xin-ren-many-jia-no-geng': [],
  'you-month-xin-ren-many-jia-with-geng': ['庚'],
  'you-month-xin-three-xin-single-ren-many-jia-geng-rich': ['庚'],
  'you-month-xin-three-xin-single-ren-many-jia-geng-ding-refined': ['丁'],
  'you-month-xin-soil-bury-metal-no-jia': [],
  'you-month-xin-soil-bury-metal-with-jia': ['甲'],
  'you-month-xin-metal-formation-no-ren-with-ding': ['丁'],
  'you-month-xin-metal-formation-no-ren-no-ding': [],
  'you-month-xin-metal-formation-ren-high': [],
  'you-month-xin-white-tiger': [],
  'you-month-xin-white-tiger-with-fire-ordinary': [],
  'you-month-xin-pure-ji-monastic': [],
  'you-month-xin-ji-with-geng-jia-hidden-leisure': [],
  'you-month-xin-water-flood-no-wu': [],
  'you-month-xin-water-flood-hidden-wu-artistry': ['戊'],
  'you-month-xin-yi-wood-no-geng-ren': [],
  'you-month-xin-yi-wood-with-geng': ['庚'],
  'you-month-xin-wuzi-chaoyang-authority': [],
  'you-month-xin-wuzi-chaoyang': [],
  'xu-month-xin-ren-jia-all': [],
  'xu-month-xin-jia-visible-ren-hidden': [],
  'xu-month-xin-ren-visible-jia-hidden-with-wu': [],
  'xu-month-xin-heavy-earth-ren-visible-jia-hidden-rich': ['壬'],
  'xu-month-xin-wood-many-earth-thick-no-water-ordinary': [],
  'xu-month-xin-wood-earth-double-gui-rich-hardship': [],
  'xu-month-xin-ji-visible-gui-no-ren-scholarly': [],
  'xu-month-xin-many-ji-gui-no-ren-cloudy-rich': [],
  'xu-month-xin-no-ren-jia-bing-xin-slight-noble': [],
  'xu-month-xin-no-ren-jia-bing-xin-with-chen-glory': [],
  'hai-month-xin-ren-bing-all': [],
  'hai-month-xin-bing-visible-ren-hidden': [],
  'hai-month-xin-ren-visible-bing-hidden': [],
  'hai-month-xin-ren-bing-hidden': [],
  'hai-month-xin-ren-many-no-wu': [],
  'hai-month-xin-wu-ren-storage': [],
  'hai-month-xin-wu-many-ren-few-fame': [],
  'hai-month-xin-jia-many-wu-few-art': [],
  'hai-month-xin-ji-many-with-wu-honest': [],
  'hai-month-xin-water-many-no-wu-bing': [],
  'zi-month-xin-ren-bing-all-no-wu-gui': [],
  'zi-month-xin-ren-hidden-bing-visible': [],
  'zi-month-xin-gui-visible-bing-visible-no-ren': [],
  'zi-month-xin-ren-many-with-wu-bing-jia': [],
  'zi-month-xin-ren-many-no-wu-bing': [],
  'zi-month-xin-ren-many-jia-yi-heavy-no-bing': [],
  'zi-month-xin-water-formation-gui-two-wu': ['戊'],
  'zi-month-xin-water-formation-gui-no-wu': [],
  'zi-month-xin-run-down-prosper': [],
  'zi-month-xin-run-down-no-metal-monastic': [],
  'zi-month-xin-wood-formation-ding-wu-merit': [],
  'chou-month-xin-bing-ren-all': [],
  'chou-month-xin-bing-ren-hidden': [],
  'chou-month-xin-bing-only-no-ren': [],
  'chou-month-xin-ren-only-no-bing': [],
  'chou-month-xin-many-bing-no-ren-gui-trade': [],
  'chou-month-xin-water-many-earth-fire-peace': [],
  'yin-month-xin-ji-ren-visible-geng-hidden-jia-control': ['庚'],
  'yin-month-xin-ji-visible-jia-hidden-alt-grace': [],
  'yin-month-xin-ren-visible-no-ji-geng-poor': [],
  'yin-month-xin-ren-visible-geng-no-ji-incomplete': [],
  'yin-month-xin-bing-visible-martial': [],
  'yin-month-xin-fire-formation-ren-only-ordinary': [],
  'yin-month-xin-fire-formation-geng-ren-all-distinguished': [],
  'yin-month-xin-water-formation-no-bing-ordinary': [],
  'yin-month-xin-water-formation-bing-visible-rich': [],
  'yin-month-xin-mao-day-zi-hour-chaoyang': [],
  'mao-month-xin-ren-jia-all-noble': [],
  'mao-month-xin-ren-sits-hai-no-earth-well-off': [],
  'mao-month-xin-shen-hidden-ren-alt-fame': [],
  'mao-month-xin-ren-wu-visible-no-jia-ordinary': [],
  'mao-month-xin-ren-wu-with-yi-scholarly-false': [],
  'mao-month-xin-ren-flood-with-wu-auspicious': ['戊'],
  'mao-month-xin-ren-flood-no-wu-meager': [],
  'mao-month-xin-no-ren-ordinary': [],
  'mao-month-xin-wood-formation-with-geng-rich': [],
  'mao-month-xin-wood-formation-no-geng-ordinary': [],
  'mao-month-xin-fire-formation-double-ren-marvel': [],
  'mao-month-xin-fire-formation-base-low': [],
  'mao-month-xin-pure-ren-no-bing-prominent': [],
  'mao-month-xin-ren-bing-all-great-wealth': [],
  'yin-month-ren-geng-bing-wu': ['庚', '丙', '戊'],
  'yin-month-ren-geng-bing-first': ['庚', '丙'],
  'yin-month-ren-geng-bing-wu-visible': [],
  'yin-month-ren-geng-first-bing-assist': ['庚', '丙'],
  'mao-month-ren-wu-xin-visible': [],
  'mao-month-ren-wu-xin-first': ['戊', '辛', '庚'],
  'chen-month-ren-jia-geng-first': ['甲', '庚'],
  'chen-month-ren-jia-geng-visible': [],
  'chen-month-ren-jia-visible-geng-hidden': [],
  'si-month-ren-water-self-support': ['壬'],
  'wu-month-ren-gui-geng': ['癸', '庚'],
  'wei-month-ren-xin-jia-gui': ['辛', '甲', '癸'],
  'wei-month-ren-xin-jia-visible': ['辛', '甲'],
  'wei-month-ren-xin-hidden-jia-visible': ['甲'],
  'shen-month-ren-wu-ding': ['戊', '丁'],
  'you-month-ren-jia-drain-soil': ['甲', '庚'],
  'you-month-ren-no-jia-gold-source': ['庚', '辛'],
  'you-month-ren-jia-wu': ['甲'],
  'xu-month-ren-jia-bing-first': ['甲', '丙'],
  'xu-month-ren-jia-bing': ['甲', '丙'],
  'hai-month-ren-wu-bing': ['戊', '丙'],
  'hai-month-ren-wu-no-bing': [],
  'hai-month-ren-no-wu-bing': [],
  'hai-month-ren-wood-formation-wu': [],
  'zi-month-ren-wu-bing': ['戊', '丙'],
  'zi-month-ren-wu-bing-visible': [],
  'zi-month-ren-wu-no-bing': [],
  'zi-month-ren-bing-no-wu': [],
  'zi-month-ren-water-formation-no-fire': [],
  'zi-month-ren-fire-formation-wealth': [],
  'chou-month-ren-xiaohan-bing-only': ['丙'],
  'chou-month-ren-dahan-bing-jia': ['丙', '甲'],
  'yin-month-gui-xin-bing': ['辛', '丙'],
  'mao-month-gui-geng-first': ['庚', '辛'],
  'chen-month-gui-qingming-bing-only': ['丙'],
  'chen-month-gui-guyu-bing-xin-jia': ['丙', '辛', '甲'],
  'wu-month-gui-geng-xin-ren-reference': ['庚', '辛', '壬'],
  'wu-wei-month-gui-metal-water-summer-rich': [],
  'wu-month-gui-metal-no-visible-water-single-water-rich': [],
  'wu-month-gui-fire-formation-no-ren-monastic': [],
  'wu-month-gui-fire-formation-two-ren-one-geng': ['壬', '庚'],
  'wu-month-gui-ji-pure-follow-kill': [],
  'wu-month-gui-metal-stem-water-formation': [],
  'wei-month-gui-geng-xin-first': ['庚', '辛'],
  'wei-month-gui-xiaoshu-metal-water-rich': [],
  'wei-month-gui-dashu-metal-rich': [],
  'wei-month-gui-ding-break-metal': ['庚', '辛'],
  'shen-month-gui-ding-first': ['丁'],
  'you-month-gui-xin-bing': ['辛', '丙'],
  'xu-month-gui-xin-jia': ['辛', '甲'],
  'hai-month-gui-geng-xin': ['庚', '辛'],
  'zi-month-gui-bing-xin': ['丙', '辛'],
  'chou-month-gui-gui-ji-party-night-ding': ['丁'],
  'chou-month-gui-gui-ji-party-no-ding': [],
  'chou-month-gui-water-formation-no-bing': [],
  'chou-month-gui-fire-formation-metal-support': [],
  'chou-month-gui-fire-formation-no-metal': [],
};
