import type { ClimateRule } from '../types';

const SOURCE_URL = 'https://zh.wikisource.org/w/index.php?title=穷通宝鉴&oldid=2294674';

function source(section: string, excerpt: string) {
  return { title: '穷通宝鉴', section, excerpt, url: SOURCE_URL };
}

/** 原文取用与实际欠缺同时成立的候选；只声明主作用，不连带提升辅助五行。 */
export const VERIFIED_CLIMATE_RULES: ClimateRule[] = [
  {
    id: 'jia-zi-ren-repeated-no-fire',
    label: '甲木子月壬重缺火照暖',
    description: '甲木子月壬水重透而丙丁皆未见时，核对丙火照暖的需要。',
    priority: 210,
    months: ['子'],
    dayMasters: ['木'],
    dayStems: ['甲'],
    minVisibleStemCounts: { 壬: 2 },
    maxStemTotalCounts: { 丙: 0, 丁: 0 },
    usefulWuxing: '火',
    favorableOrder: ['火'],
    hint: '甲木子月壬水重透、原局无火，丙火照暖与水木扶抑分别核对',
    policy: {
      mode: 'conditional',
      source: source('三冬甲木', '或壬水重出，丁火全无者，庸人也，得丙方妙。'),
      effects: [{ stem: '丙', wuxing: '火', role: '照暖', targetStems: ['甲'], rank: 'primary' }],
    },
  },
  {
    id: 'jia-chou-geng-present-no-ding',
    label: '甲木丑月庚透缺丁',
    description: '甲木丑月已有庚金透干而丁火未见时，核对庚劈甲、甲引丁的作用链。',
    priority: 210,
    months: ['丑'],
    dayMasters: ['木'],
    dayStems: ['甲'],
    requiredVisibleStems: ['庚'],
    maxStemTotalCounts: { 丁: 0 },
    usefulWuxing: '火',
    favorableOrder: ['火'],
    hint: '甲木丑月庚透缺丁，核对引丁成暖的作用及庚木根气',
    policy: {
      mode: 'within-balance',
      source: source('三冬甲木', '先用庚噼甲，方引丁火始得木火有通明之象，故丁次之。'),
      effects: [
        { stem: '丁', wuxing: '火', role: '引火成暖', targetStems: ['甲'], rank: 'primary' },
      ],
    },
  },
  {
    id: 'yi-zi-missing-bing-thaw',
    label: '乙木子月缺丙解冻',
    description: '子月乙木取丙解冻，丁火的照明作用与丙火解冻分别核对。',
    priority: 210,
    months: ['子'],
    dayMasters: ['木'],
    dayStems: ['乙'],
    maxStemTotalCounts: { 丙: 0 },
    usefulWuxing: '火',
    favorableOrder: ['火'],
    hint: '乙木子月丙火未见，取丙解冻；丁火与丙火的调候作用分别判断',
    policy: {
      mode: 'conditional',
      source: source('三冬乙木', '十一月乙木，花木寒冻，一阳来复，喜用丙火解冻。'),
      effects: [{ stem: '丙', wuxing: '火', role: '解冻', targetStems: ['乙'], rank: 'primary' }],
    },
  },
  {
    id: 'geng-chou-missing-bing-thaw',
    label: '庚金丑月缺丙解冻',
    description: '丑月先以丙解冻，再论丁炼金；解冻与炼金是两项不同作用。',
    priority: 210,
    months: ['丑'],
    dayMasters: ['金'],
    dayStems: ['庚'],
    maxStemTotalCounts: { 丙: 0 },
    usefulWuxing: '火',
    favorableOrder: ['火'],
    hint: '庚金丑月丙火未见，先核对解冻所需，再论丁火炼金',
    policy: {
      mode: 'conditional',
      source: source(
        '三冬庚金',
        '十二月庚金，寒气太重，且多湿泥，愈寒愈冻，先取丙火解冻，次取丁火炼金，甲亦不可少。',
      ),
      effects: [{ stem: '丙', wuxing: '火', role: '解冻', targetStems: ['庚'], rank: 'primary' }],
    },
  },
  {
    id: 'geng-winter-no-fire-warm',
    label: '庚金亥子月无火照暖',
    description: '亥子月庚金全无丙丁时，丙火照暖与丁火锻炼分别列为功能候选。',
    priority: 210,
    months: ['亥', '子'],
    dayMasters: ['金'],
    dayStems: ['庚'],
    maxStemTotalCounts: { 丙: 0, 丁: 0 },
    usefulWuxing: '火',
    favorableOrder: ['火'],
    hint: '庚金亥子月全无丙丁，丙火照暖为当前调候需求，丁火炼金另核条件',
    policy: {
      mode: 'conditional',
      source: source('三冬庚金', '十月庚金，水冷性寒，非丁莫造，非丙不暖。'),
      effects: [
        { stem: '丙', wuxing: '火', role: '照暖', targetStems: ['庚'], rank: 'primary' },
        { stem: '丁', wuxing: '火', role: '锻炼', targetStems: ['庚'], rank: 'secondary' },
      ],
    },
  },
  {
    id: 'xin-zi-no-fire-warm',
    label: '辛金子月无火照暖',
    description: '子月辛金全无丙丁且未成水局时，核对丙火温暖需求。',
    priority: 210,
    months: ['子'],
    dayMasters: ['金'],
    dayStems: ['辛'],
    maxStemTotalCounts: { 丙: 0, 丁: 0 },
    forbiddenFormationWuxings: ['水'],
    usefulWuxing: '火',
    favorableOrder: ['火'],
    hint: '辛金子月无火且未成水局，取丙照暖；壬水淘洗另核原局承载',
    policy: {
      mode: 'conditional',
      source: source('三冬辛金', '冬月辛金，须丙温暖方妙。'),
      effects: [{ stem: '丙', wuxing: '火', role: '照暖', targetStems: ['辛'], rank: 'primary' }],
    },
  },
  {
    id: 'gui-winter-missing-bing-thaw',
    label: '癸水子丑月缺丙解冻',
    description: '子丑月癸水缺丙时先核对解冻需求，辛金滋扶为另一作用。',
    priority: 210,
    months: ['子', '丑'],
    dayMasters: ['水'],
    dayStems: ['癸'],
    maxStemTotalCounts: { 丙: 0 },
    usefulWuxing: '火',
    favorableOrder: ['火'],
    hint: '癸水子丑月丙火未见，先论解冻，再核对生扶与制化',
    policy: {
      mode: 'conditional',
      source: source('三冬癸水', '十二月癸水，寒极成冰，万物不能舒泰，宜丙火解冻。'),
      effects: [{ stem: '丙', wuxing: '火', role: '解冻', targetStems: ['癸'], rank: 'primary' }],
    },
  },
  {
    id: 'jia-si-wu-fire-no-water-moisten',
    label: '甲木巳午月火透无水润燥',
    description: '巳午月甲木丙丁明透而壬癸皆未见时，核对癸水润燥需求。',
    priority: 210,
    months: ['巳', '午'],
    dayMasters: ['木'],
    dayStems: ['甲'],
    optionalVisibleStems: ['丙', '丁'],
    maxStemTotalCounts: { 壬: 0, 癸: 0 },
    usefulWuxing: '水',
    favorableOrder: ['水'],
    hint: '甲木巳午月火透无水，癸水润燥为当前需求；丁庚作用另看制化',
    policy: {
      mode: 'conditional',
      source: source('三夏甲木', '四月甲木退气，丙火司权，先癸后丁。'),
      effects: [{ stem: '癸', wuxing: '水', role: '润燥', targetStems: ['甲'], rank: 'primary' }],
    },
  },
  {
    id: 'yi-summer-fire-formation-no-water',
    label: '乙木夏月火局无水滋润',
    description: '乙木夏月丙火明透、支成火局且无壬癸时，核对水润燥与救泄的作用。',
    priority: 210,
    months: ['巳', '午', '未'],
    dayMasters: ['木'],
    dayStems: ['乙'],
    requiredVisibleStems: ['丙'],
    requiredFormationWuxings: ['火'],
    maxStemTotalCounts: { 壬: 0, 癸: 0 },
    usefulWuxing: '水',
    favorableOrder: ['水'],
    hint: '乙木夏月丙透火局、原局无水，核对癸水滋润与壬水解燥的作用',
    policy: {
      mode: 'conditional',
      source: source('三夏乙木', '乙木重逢火位，名为气散之文，支成火局，泄乙精神，须用癸滋。'),
      effects: [
        { stem: '癸', wuxing: '水', role: '滋润救泄', targetStems: ['乙'], rank: 'primary' },
      ],
    },
  },
  {
    id: 'wu-wu-fire-formation-no-water',
    label: '戊土午月火局无水润燥',
    description: '戊土午月支成火局、壬癸未见时，取壬润燥，保留壬癸作用强弱的区别。',
    priority: 210,
    months: ['午'],
    dayMasters: ['土'],
    dayStems: ['戊'],
    requiredFormationWuxings: ['火'],
    maxStemTotalCounts: { 壬: 0, 癸: 0 },
    usefulWuxing: '水',
    favorableOrder: ['水'],
    hint: '戊土午月火局无水，壬水润燥为当前需求，甲木疏土另核条件',
    policy: {
      mode: 'conditional',
      source: source('三夏戊土', '五月戊土，仲夏火炎，先看壬水，次取甲木，丙火酌用，用癸力微。'),
      effects: [{ stem: '壬', wuxing: '水', role: '润燥', targetStems: ['戊'], rank: 'primary' }],
    },
  },
];
